service: kjglass-mailer

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  email:
    handler: index.handler
    environment:
      SENDER_EMAIL: ${env:SENDER_EMAIL}
      MAIL_SERVICE: ${env:MAIL_SERVICE},
      MAIL_USER: ${env:MAIL_USER},
      MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    events:
      - http:
          path: send-email
          method: POST
          cors: true
